language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/mbed-blink
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-ethernet
  - PLATFORMIO_PROJECT_DIR=examples/sdkexpresso-basic
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization

# Zephyr framework doesn't support python 2
jobs:
  exclude:
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: njzMf+A7GH8qll87xvYxc7dtYfAz2V+LB/TloRBeTlqzCafb+pzFbSNQddsMhgBGPvYCn1BwOGArbCigB8vK8tAld9j9/mT4rnQN13hh7nCINsUi/NI1SmRB9WBJ8AuFHhvd3VZXwBQh1ok13O0roL/tbfn88FZOhYLF0zOywDmzfDXCUBnYZxNZ5uklNJR171i8XRRE+elE/FFByrPRPTqhfMjzp1EirLu5zRjHrEzmeWFUzvK60hSlW+GRWpWLYVsHXtH6egH3pYZH3ipq3WYbda3PCFFL08p1I339rHRBk3GK6xn4dA4BEZ9gLKHHPufXVZtJWqIhzdGlQeqjcNRlclgmDAGuL+5LUEseOwzOz6f2om0k+WtRJGGy5brgdsrszX6ix037OYXTIN57wbslEkPLJAEndXSFrmE8AIoMLlmZBVsC/xVW48+BQXD3R6mUSSDcaAI+m32b2K/LLjyC2toh+5bJjSTucXP208SwngoTolefzvT7VAKhafw68pv0Kqf/W3ez4dBxSfNSVBoLikqfdqEkK4SCsQqBoUkZxRegpc8bGAxayrbGUvRwo8XZ+7jof7hRpbz9n8U/LrLGLKPOrnJ7+hd2C94dSuQUw7naFRObmLKOC5q2I3sQZYg7A7/7qU1DxhSsXpIQjJp26liAx6jsg0lEVRwQ4gE=
    on_failure: always
    on_success: change
